version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #django인지 fastapi인지는 여기만 바뀌면 됨  
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"